/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_sourcetree;

import java.text.Normalizer;
import javax.swing.UIManager;

/**
 *
 * @author Leo
 */
public class Interfaz extends javax.swing.JFrame {
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        try{
            UIManager.setLookAndFeel("javax.swing.plaf.MetalLookAndFeel");
        }
        catch(Exception ex){
            
        }
        this.setVisible(true);
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entrada1 = new javax.swing.JTextField();
        Entrada2 = new javax.swing.JTextField();
        Entrada3 = new javax.swing.JTextField();
        Resultado = new javax.swing.JLabel();
        Hipotenusa = new javax.swing.JButton();
        Vocales = new javax.swing.JButton();
        Reversa = new javax.swing.JButton();
        Regla3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Resultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resultado.setForeground(new java.awt.Color(0, 153, 153));
        Resultado.setText("Resultado");

        Hipotenusa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Hipotenusa.setText("Hipotenusa");
        Hipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HipotenusaActionPerformed(evt);
            }
        });

        Vocales.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Vocales.setText("Vocales");
        Vocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VocalesActionPerformed(evt);
            }
        });

        Reversa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Reversa.setText("Reversa");
        Reversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReversaActionPerformed(evt);
            }
        });

        Regla3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Regla3.setText("Regla de 3");
        Regla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regla3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Entrada 1:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Entrada 2:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Entrada 3:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Hipotenusa)
                        .addGap(18, 18, 18)
                        .addComponent(Vocales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(Reversa)
                        .addGap(18, 18, 18)
                        .addComponent(Regla3)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Entrada3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Resultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(Entrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Entrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Entrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Entrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Entrada3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hipotenusa)
                    .addComponent(Vocales)
                    .addComponent(Reversa)
                    .addComponent(Regla3))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HipotenusaActionPerformed
       if (!Entrada1.getText().equals("") && !Entrada2.getText().equals("")){
        try{
            Resultado.setText(calculoHipotenusa(Double.parseDouble(Entrada1.getText()), Double.parseDouble(Entrada2.getText())));
        }   
        catch(Exception e){
            Resultado.setText("Los campos no son validos");
        }
        }
        else{
            Resultado.setText("Los campos estan vacios");
        }
    }//GEN-LAST:event_HipotenusaActionPerformed

    private void VocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VocalesActionPerformed
       Resultado.setText(calculoVocales(Entrada1.getText()));
    }//GEN-LAST:event_VocalesActionPerformed

    private void ReversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReversaActionPerformed
       if (!Entrada1.getText().equals("") && !Entrada2.getText().equals("")){
       Resultado.setText(calculoReversa(Entrada1.getText()) + " " + calculoReversa(Entrada2.getText()));  
        }
        else{
            Resultado.setText("Los campos estan vacios");
       }      
    }//GEN-LAST:event_ReversaActionPerformed

    private void Regla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regla3ActionPerformed
        if (!Entrada1.getText().equals("") && !Entrada2.getText().equals("") && !Entrada3.getText().equals("")){
        try{
             Resultado.setText(calculoRegla3(Double.parseDouble(Entrada1.getText()), Double.parseDouble(Entrada2.getText()), Double.parseDouble(Entrada3.getText())));
        }   
        catch(Exception e){
            Resultado.setText("Los campos no son validos");
        }
        }
        else{
            Resultado.setText("Los campos estan vacios");
        }
    }//GEN-LAST:event_Regla3ActionPerformed

    
    private String calculoHipotenusa(double catetoA, double catetoB){
        double catA= Math.pow(catetoA,2);
        double catB= Math.pow(catetoB,2);
        double radicando = catA + catB;
        return String.valueOf(Math.pow(radicando,0.5));
    }
    
    public String calculoVocales(String palabra){
        String normalizar = Normalizer.normalize(palabra, Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "");
     
        String normalizado = normalizar.replaceAll("[^\\p{ASCII}]", "").toLowerCase();
        System.out.println(normalizado);
        boolean permiso[]= {false,false,false,false,false};
        for(int contador=normalizado.length()-1;contador>=0;contador--){
            int codigo = (int)normalizado.charAt(contador);
            
            switch(codigo){
                case 97:
                    permiso[0]=true;  //a
                    break;
                case 101:
                    permiso[1]=true;  //e
                    break;
                case 105:
                    permiso[2]=true;  //i
                    break;
                case 111:
                    permiso[3]=true;  //o
                    break;
                case 117:
                    permiso[4]=true;  //u
                    break;
            }            
        }
                
        for(int contador=0;contador<permiso.length;contador++){
            if (!permiso[contador]){
                return "No Cumple";
            }
        }    
        
        return "Cumple";
    }
    
    public String calculoReversa(String palabra){
        String reves = "";
        for(int contador=palabra.length()-1;contador>=0;contador--){
            reves += palabra.charAt(contador);
        }
        return reves;
    }
    
    public String calculoRegla3(double A, double X, double B){
        double resultado = X*B/A; // A:X::B:Y
        return String.valueOf(resultado);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entrada1;
    private javax.swing.JTextField Entrada2;
    private javax.swing.JTextField Entrada3;
    private javax.swing.JButton Hipotenusa;
    private javax.swing.JButton Regla3;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton Reversa;
    private javax.swing.JButton Vocales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
